# Generated by Django 4.2.6 on 2023-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('experiencia', models.CharField(choices=[('Menor a 5 años', 'Menor a 5 años'), ('Mayor a 5 años', 'Mayor a 5 años'), ('Mayor a 10 años', 'Mayor a 10 años')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('peso', models.CharField(choices=[('Infantil', 'Infantil'), ('Adolescencia', 'Adolescencia'), ('Pluma', 'Pluma'), ('Ligero', 'Ligero'), ('Semi-Pesado', 'Semi-Pesado'), ('Pesado', 'Pesado')], max_length=16)),
                ('edad', models.CharField(choices=[('5 a 12 años', '5 a 12 años'), ('13 a 17 años', '13 a 17 años'), ('Mayor de edad', 'Mayor de edad')], max_length=16)),
                ('peleas', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('experiencia', models.CharField(choices=[('Menor a 5 años', 'Menor a 5 años'), ('Mayor a 5 años', 'Mayor a 5 años'), ('Mayor a 10 años', 'Mayor a 10 años')], max_length=16)),
            ],
        ),
    ]
